### PR TITLE
paas_app_wrapper.sh: make aware of notify-antivirus-ecs-fixup

### PR DESCRIPTION
**Pull request by risicle**
Missed this from #137

---

🚨⚠️ This will be deployed automatically all the way to production when you click merge ⚠️🚨

For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on deployment](https://github.com/alphagov/notifications-manuals/wiki/Merging-and-deploying#deployment)

### CODE REVIEW

**Comment by klssmith** [comment]
Won't this stop `notify-antivirus` being deployed?

**Comment by risicle** [comment]
I didn't bleedin push my bleedin updated branch...

**Comment by risicle** [comment]
There we go well caught.

**Review by idavidmcdonald — APPROVED** [review]
Tested locally, works

**Pull request merged**
